"""setup with neon

Revision ID: 0c6833d9bf1a
Revises: 
Create Date: 2025-12-25 20:56:15.030257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c6833d9bf1a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotel_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_name', sa.String(), nullable=False),
    sa.Column('hotel_phone_no', sa.BigInteger(), nullable=False),
    sa.Column('hotel_email', sa.String(), nullable=False),
    sa.Column('hotel_password', sa.String(), nullable=False),
    sa.Column('hotel_address', sa.String(), nullable=False),
    sa.Column('hotel_lan', sa.Float(), nullable=False),
    sa.Column('hotel_long', sa.Float(), nullable=False),
    sa.Column('hotel_rating', sa.Float(), nullable=True),
    sa.Column('hotel_status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hotel_email')
    )
    op.create_index(op.f('ix_hotel_details_id'), 'hotel_details', ['id'], unique=False)
    op.create_table('category_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.Column('category_description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_details_hotel_id'), 'category_details', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_category_details_id'), 'category_details', ['id'], unique=False)
    op.create_table('food_item_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('item_description', sa.String(), nullable=True),
    sa.Column('item_price', sa.Float(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category_details.id'], ),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_item_details_hotel_id'), 'food_item_details', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_food_item_details_id'), 'food_item_details', ['id'], unique=False)
    op.drop_index(op.f('ix_driver_details_id'), table_name='driver_details')
    op.drop_table('driver_details')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('driver_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('drive_bike_no', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('drive_license_no', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('drive_phone_no', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('drive_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('drive_address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('driver_lan', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('driver_long', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('driver_status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('driver_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('driver_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('driver_details_pkey')),
    sa.UniqueConstraint('driver_email', name=op.f('driver_details_driver_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_driver_details_id'), 'driver_details', ['id'], unique=False)
    op.drop_index(op.f('ix_food_item_details_id'), table_name='food_item_details')
    op.drop_index(op.f('ix_food_item_details_hotel_id'), table_name='food_item_details')
    op.drop_table('food_item_details')
    op.drop_index(op.f('ix_category_details_id'), table_name='category_details')
    op.drop_index(op.f('ix_category_details_hotel_id'), table_name='category_details')
    op.drop_table('category_details')
    op.drop_index(op.f('ix_hotel_details_id'), table_name='hotel_details')
    op.drop_table('hotel_details')
    # ### end Alembic commands ###
