"""Change phone to string

Revision ID: c3592c1c2c1b
Revises: 8c8495f59ab0
Create Date: 2025-12-25 14:34:17.892945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3592c1c2c1b'
down_revision: Union[str, Sequence[str], None] = '8c8495f59ab0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_details', sa.Column('driver_email', sa.String(), nullable=False))
    op.alter_column('driver_details', 'driver_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_unique_constraint(None, 'driver_details', ['driver_email'])
    op.drop_column('driver_details', 'drivee_email')
    op.drop_column('driver_details', 'drive_password_confirm')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_details', sa.Column('drive_password_confirm', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('driver_details', sa.Column('drivee_email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'driver_details', type_='unique')
    op.alter_column('driver_details', 'driver_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('driver_details', 'driver_email')
    # ### end Alembic commands ###
