"""Initial migration

Revision ID: d8b279dc9d8a
Revises: 
Create Date: 2025-12-25 13:21:30.798378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8b279dc9d8a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_name', sa.String(), nullable=False),
    sa.Column('drive_bike_no', sa.String(), nullable=False),
    sa.Column('drive_license_no', sa.Integer(), nullable=False),
    sa.Column('drive_phone_no', sa.Integer(), nullable=False),
    sa.Column('drivee_email', sa.String(), nullable=False),
    sa.Column('drive_password', sa.String(), nullable=False),
    sa.Column('drive_address', sa.String(), nullable=False),
    sa.Column('driver_lan', sa.String(), nullable=False),
    sa.Column('driver_long', sa.String(), nullable=False),
    sa.Column('driver_status', sa.Boolean(), nullable=True),
    sa.Column('driver_rating', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_details_id'), 'driver_details', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_driver_details_id'), table_name='driver_details')
    op.drop_table('driver_details')
    # ### end Alembic commands ###
